version: "3"
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/schooldb -user=postgres -password=postgres_password migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: schooldb
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
