name: CI

on:
  pull_request:
    branches:
      - develop
      - stage
      - preprod
      - master

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        timeout-minutes: 10
        run: npm run test:ci:cov
